#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/plugin-runtime.sh"

PYTHON_BIN="$("$SCRIPT_DIR/plugin-bootstrap.sh")"
MEMPALACE_BIN="$(dirname "$PYTHON_BIN")/mempalace"
PLUGIN_DATA="$(plugin_runtime_resolve_data_dir)"
PLUGIN_ROOT="$(plugin_runtime_resolve_root)"
PALACE_PATH="$(
  plugin_runtime_first_set \
    CLAUDE_PLUGIN_OPTION_PALACE_PATH \
    CODEX_PLUGIN_OPTION_PALACE_PATH \
    PLUGIN_OPTION_PALACE_PATH \
  || true
)"

if [[ -n "$PALACE_PATH" ]]; then
  export MEMPALACE_PALACE_PATH="$PALACE_PATH"
fi

export MEMPALACE_STATE_DIR="${MEMPALACE_STATE_DIR:-$PLUGIN_DATA/hook-state}"
export MEMPALACE_SAVE_INTERVAL="${MEMPALACE_SAVE_INTERVAL:-${CLAUDE_PLUGIN_OPTION_SAVE_INTERVAL:-${CODEX_PLUGIN_OPTION_SAVE_INTERVAL:-10}}}"
export MEMPALACE_STARTUP_WING="${MEMPALACE_STARTUP_WING:-${CLAUDE_PLUGIN_OPTION_STARTUP_WING:-${CODEX_PLUGIN_OPTION_STARTUP_WING:-claude}}}"
export MEMPALACE_PLUGIN_DATA="$PLUGIN_DATA"
export MEMPALACE_PLUGIN_ROOT="$PLUGIN_ROOT"
export MEMPALACE_BIN_OVERRIDE="$MEMPALACE_BIN"
export PATH="$(dirname "$PYTHON_BIN"):$PATH"
